### ISSUE TITLE
Tord's private todo list

### ISSUE THREAD

**Issue by SunyataZero** [SunyataZero/buddhist-well-being-pyqt5#5]
* [x] menu: File -> export
* [ ] menu: File -> clear db (development only)
* [ ] menu: File -> backup db
* [ ] put add new diary entry at the bottom instead of at the top? And invert the ordering of the diary entries at the same time
  * [scroll to bottom](http://stackoverflow.com/questions/811532/how-to-scroll-automaticaly-within-a-tkinter-message-window)
* [ ] Stats for each of the ten observances

***

# Finding more people

Type of skills:
* Design
* Testing
* Programming

Places to look:
* Openhatch.org
* #openhatch
* sourceforge
* https://sourceforge.net/p/forge/helpwanted/
* twitter
* facebook
